// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Transforms = {
    lighten: function(color, percentage) {
      var hsl;
      hsl = color.mod({
        l: color.constrain(color.lightness(), percentage, [0, 100], '+')
      });
      return color.rgb2hex(color.hsl2rgb(hsl));
    },
    darken: function(color, percentage) {
      var hsl;
      hsl = color.mod({
        l: color.constrain(color.lightness(), percentage, [0, 100], '-')
      });
      return color.rgb2hex(color.hsl2rgb(hsl));
    },
    saturate: function(color, percentage) {
      var hsl;
      hsl = color.mod({
        s: color.constrain(color.saturation(), percentage, [0, 100], '+')
      });
      return color.rgb2hex(color.hsl2rgb(hsl));
    },
    desaturate: function(color, percentage) {
      var hsl;
      hsl = color.mod({
        s: color.constrain(color.saturation(), percentage, [0, 100], '-')
      });
      return color.rgb2hex(color.hsl2rgb(hsl));
    },
    adjust_hue: function(color, degrees) {
      var hsl;
      hsl = color.mod({
        h: color.constrain_degrees(color.hue(), degrees)
      });
      return color.rgb2hex(color.hsl2rgb(hsl));
    }
  };

}).call(this);
